### ISSUE TITLE
Pulls based on task creation date as well

### ISSUE THREAD

**Issue by PHactotum** [gr0undzer0/xp#2]
When using both task creation date and task finish dates, XP will list the tasks as being completed for both dates.  Example:
Done contains:
x 2014-06-16 2014-06-15 Test XP
# Results in:
# Sunday : 2014-06-15 
# x 2014-06-16 2014-06-15 Test XP
# Monday : 2014-06-16 

x 2014-06-16 2014-06-15 Test XP

**Comment by gr0undzer0** [comment]
Fixed in latest commit 2c01c89. Please let me know if this resolves the issue for you. Thanks for finding this.
